resolver: lts-10.4
image:
  container:
    name: snoyberg/haskellers
    base: fpco/stack-run
    add:
        static: /app/static
        config: /app/config

extra-deps:
- git: https://github.com/snoyberg/gitrev.git
  commit: 6a1a639f493ac08959eb5ddf540ca1937baaaaf9
