Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  copyright: Insert copyright statement here
  allowAuthDummy: False
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  <<: *defaults
  # We want to be sure, auth Dummy is not enabled on production.
  allowAuthDummy: False
